addSbtPlugin("com.typesafe.play"    % "sbt-plugin"            % "2.6.13")
addSbtPlugin("com.gu"               % "sbt-riffraff-artifact" % "1.1.4")
addSbtPlugin("com.typesafe.sbt"     % "sbt-native-packager"   % "1.2.0")
addSbtPlugin("com.eed3si9n"         % "sbt-buildinfo"         % "0.9.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-digest"            % "1.1.4")
